### ISSUE TITLE
Cannot use negative numbers properly

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/BetterLoadingScreen#21]
Using "-32" fails, but "0-32" doesn't.

**Comment by Tsyklop** [comment]
Tell me please. The length of the progress bar can be 400 pixels?

**Comment by AlexIIL** [comment]
Er, wrong issue and yes? (I'm assuming you mean in response to https://github.com/AlexIIL/BetterLoadingScreen/issues/24)

**Comment by Tsyklop** [comment]
@AlexIIL Not really. This bug is gone. I have a slightly different problem.
I made a picture with progress bars 400x400 pixels. The height of each progress bar I have 32 pixels. And the result here is:
![default](https://cloud.githubusercontent.com/assets/6783568/8544673/09cf9314-24b0-11e5-8755-ff7195cad7e3.png)

That file images.json:
http://pastebin.com/RPT8C9sm


If I make the width of 256 and a height of 16 in the config is all right.
But why is this happening when I picture sizes 400x400 and get yourself progress bars width and height 400h32?

**Comment by AlexIIL** [comment]
Oh, sorry, its to do with how minecraft interprets image sizes. It has to assume that all images are 256x256 in size, so you have to change the texture height and width to be between 0 and 256 :/ (Can I see your image file?)

(Internally, it changes all images sizes to be decimals between 0 and 1, so it divides the pixels by 256... which means that you should use an image of sizes that are multiples of 256, like 512, for the image to fit properly and use a good number)

**Comment by AlexIIL** [comment]
(I don't think I can change it... but I will have a look)

**Comment by Tsyklop** [comment]
512x512 will work fine? Or only 256x256?

![progressbars1](https://cloud.githubusercontent.com/assets/6783568/8544820/497e69bc-24b1-11e5-9820-2bfdf4f1622a.png)

**Comment by AlexIIL** [comment]
512x512 would be fine, but you would have to divide the pixel positions by 2 (so if your progress bar is 32 pixels high, you would use 16 as the hight in the config)

**Comment by Tsyklop** [comment]
@AlexIIL That is, the progress bar should be the size 512х16?

**Comment by AlexIIL** [comment]
Oh sorry, for that image is fine, but in your config you would have

    "texture": {
      "x": 0,
      "y": 0,
      "width": 256,
      "height": 16
    }

And it should display the entire progress bar

**Comment by AlexIIL** [comment]
Ignore that last comment pls!

**Comment by AlexIIL** [comment]
@AlexIIL That is, the progress bar should be the size 512х16?

Sorry, yes. But 512x32 would also be ok

**Comment by Tsyklop** [comment]
@AlexIIL Thanks!

**Comment by AlexIIL** [comment]
Is it all working properly now?

**Comment by Tsyklop** [comment]
@AlexIIL Well, I need to alter the image size of 512x512, and then I can say

**Comment by Tsyklop** [comment]
@AlexIIL 512x512 not working. Only 256x256

**Comment by AlexIIL** [comment]
Huh. Does it not work at all or does it only partially work?

**Comment by AlexIIL** [comment]
(And can you show me the image and your config file)

**Comment by Tsyklop** [comment]
@AlexIIL I made a picture size of 512x512. Progress bar sizes 512h32.
I ran the client.
And get this:
![2](https://cloud.githubusercontent.com/assets/6783568/8566537/6deb82ce-2567-11e5-9dfc-a46a9fba8ca1.png)

Config: http://pastebin.com/PMVV8SrB

**Comment by AlexIIL** [comment]
Change the texture width and height from 512, 32 to 256, 16 for both, and change the y value for the dynamic percentage to 17 and it should work fine

**Comment by AlexIIL** [comment]
(The values for the texture go from 0 at one end of the texture to 256 at the other end)

**Comment by Tsyklop** [comment]
@AlexIIL  Well, I did, and everything is fine.
I wrote that 512x512 does not work simply.

**Comment by AlexIIL** [comment]
Ok. I guess I'm going to need to put that on a wiki and explain it properly to avoid confusion

**Comment by Tsyklop** [comment]
@AlexIIL Ok.
I have a question. Will the implementation of the change buttons in Gui? (Singleplayer, multiplayer, options and so on)

**Comment by AlexIIL** [comment]
No. Nothing I do affects the main menu or anything after that

**Comment by Tsyklop** [comment]
@AlexIIL Thanks
