### ISSUE TITLE
Improper display

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#26]
Image file:
![progressbars1](https://cloud.githubusercontent.com/assets/6783568/8639186/b1630768-28da-11e5-828a-5ca518119089.png)

Progress bar in Game:
![default](https://cloud.githubusercontent.com/assets/6783568/8639187/bd03b1c6-28da-11e5-86b5-5e3d9f8d6a76.png)

wtf and how?

Config: http://pastebin.com/nusQ3THd

**Comment by AlexIIL** [comment]
Its transparent. I don't currently set up OpenGL for transparency, so it is just taking the colour values, and ignoring the transparency. I could change this, except that its on a white background so why not just change the image to the colour you want, minus the alpha.

**Comment by AlexIIL** [comment]
Although the y values look fine to me in the config, something is obviously not right...

**Comment by AlexIIL** [comment]
Ok fine, I will enable transparancy...

**Comment by Tsyklop** [comment]
I would be very grateful

**Comment by Tsyklop** [comment]
fixed?

**Comment by AlexIIL** [comment]
I haven't tested or pushed it yet sorry :(

**Comment by AlexIIL** [comment]
I'm building a new version now, should be on curse shortly

**Comment by AlexIIL** [comment]
Uploaded to curse, waiting for the approval. Sorry for the delay on such a simple problem.

**Comment by Tsyklop** [comment]
Working. THX

**Comment by AlexIIL** [comment]
:)
