### ISSUE TITLE
Tell CurseForge that AlexIILLib is required for 1.8 versions.

### ISSUE THREAD

**Issue by RAnders00** [AlexIIL/BetterLoadingScreen#3]
It's possible to say that downloads require other projects as dependencies. [Example of usage here.](http://minecraft.curseforge.com/mc-mods/222880-thermal-foundation/files/2221827) Why is this something important? If users install your mod using the Curse Client, the Curse Client is able to automatically install AlexIILLib for them.

**Comment by AlexIIL** [comment]
Fixed for the latest file, i will have to remember to do so for all future files
