### ISSUE TITLE
Change the file path progressBars.png

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#34]
I fit into images.json this way:
minecraft: textures / gui / title / progressBars.png
But progress bar loaded from jar file mod.

And further. What did change in version 1.3.8?

**Comment by AlexIIL** [comment]
Are you trying to change the text inside of images.json, or are you creating a progressBars.png file somewhere? (And can I have the text inside of images.json if you did change it)

**Comment by AlexIIL** [comment]
Also you need to override "betterloadingscreen:textures/gui/title/progressBars.png" instead of "minecraft:"

**Comment by Tsyklop** [comment]
I moved the file from jar BTS file progressBars.png and tossed a file Forge.
And in the file path images.json changed. Minecraft is the path to the texture of the Forge or resoursepack

**Comment by AlexIIL** [comment]
Ok, that does sound strange

**Comment by Tsyklop** [comment]
Sorry. Everything works correctly
