### ISSUE TITLE
Russian language is not displayed correctly

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#38]
![default](https://cloud.githubusercontent.com/assets/6783568/9625390/6eec7b56-515e-11e5-89c5-af0bae7f1315.png)

Fix please)

**Comment by AlexIIL** [comment]
Hmmm. I have no idea what's causing this, or how to go about fixing it. Could you screenshot the contents of the "assets/betterloadingscreen/land/ru_RU.lang" file inside of your mod file?

**Comment by Tsyklop** [comment]
![default](https://cloud.githubusercontent.com/assets/6783568/9630286/e6afacda-5181-11e5-81e7-9ee6127a6d00.png)
@AlexIIL this?

**Comment by AlexIIL** [comment]
Yes, thanks.

**Comment by AlexIIL** [comment]
Although that just means that you have a valid jar file so that isn't the issue :(

**Comment by Tsyklop** [comment]
@AlexIIL And what could be the problem? Maybe not the encoding?

Russian translation generally works in other modes ..

**Comment by AlexIIL** [comment]
Perhaps I'm accidentally mangling it somewhere... what version are you using? Also, did you notice this in any older versions?

**Comment by AlexIIL** [comment]
Hmm, I cant seem to reproduce this with 1.3.8.

**Comment by Tsyklop** [comment]
@AlexIIL This bug is on version 1.3.8 and version 1.3.6. I'm using 1.3.8.

So I learned something.
Perhaps it affects some mod. But what is hard to say. I removed all the ods and started only with your mod the game and the text was in Russian.

**Comment by AlexIIL** [comment]
Ok thats interesting... can I see a mod list?

**Comment by Tsyklop** [comment]
@AlexIIL Yes of course.

(I took a crash log.)

http://pastebin.com/XBg29zJM

Add.I noticed that these characters are not correct file ascii.png set resoursepack.

**Comment by AlexIIL** [comment]
Apparently its something to do with client fixer. (I replicated it with just that, so I should be able to fix it)

**Comment by Tsyklop** [comment]
I deleted ClientFixer and nothing has changed...

**Comment by AlexIIL** [comment]
Strange... :(

**Comment by Tsyklop** [comment]
heh. I deleted ClientFixer and OptiFine and all was well

**Comment by AlexIIL** [comment]
Hmmm. What version of optifine were you using? (I kinda want to make this work for you, I assume optifine and client fixer are important)

**Comment by Tsyklop** [comment]
Yes important to me.
OptiFine_1.7.10_HD_U_C1

**Comment by AlexIIL** [comment]
I installed just optifine HD_U_C1 and it worked, anything involving ClientFixer fails for some reason...

**Comment by Tsyklop** [comment]
and I have to Optifine does not work ...

**Comment by Tsyklop** [comment]
What to do?

**Comment by AlexIIL** [comment]
OH! I know whats happening. I use the ascii font texture in BLS, but ClientFixer changes the ascii file locations everywhere else to make it work. So I just need to let you change the font texture from "ascii" to "ascii_fat"

**Comment by Tsyklop** [comment]
Good. I am waiting)

**Comment by AlexIIL** [comment]
Hang on. Inside of your "config" directory and then "betterloadingscreen" there should be a file named "images.json". Can you change every "textures/font/ascii.png" to "textures/font/ascii_fat.png"?

**Comment by AlexIIL** [comment]
Thats also really annoying to do so I will still make a proper fix soon

**Comment by Tsyklop** [comment]
I have not found ascii_fat.png. I have ascii_sga.png.

And gives an error:
http://pastebin.com/SDcpYJmR

**Comment by Tsyklop** [comment]
Yes! Everything is working! Thank you so much!

**Comment by AlexIIL** [comment]
hang on, let me make a config file option for this otherwise you would have to change images.json every single time to fix this :)

**Comment by Tsyklop** [comment]
After starting images.json not changed.

**Comment by Tsyklop** [comment]
Ok. fix this)
