### ISSUE TITLE
Progress bar position doesn't account for resourcepack-added splash logo

### ISSUE THREAD

**Issue by Gotolei** [AlexIIL/BetterLoadingScreen#4]
https://i.imgur.com/PWyBvrV.png

Perhaps have it display lower down (at least by default), or detect the dimensions of the image and act accordingly?

**Comment by AlexIIL** [comment]
Might try detecting the image dimensions, but I don't know how that will work with a configuration supplied y offset value (I am working on a build that contains some more config options, and that might be the easiest way of doing it). Or would it make any sense to load the y offset from the resource pack itself (by adding in an assets/betterloadingscreen/config.cfg file, that can be loaded from any resource pack)

**Comment by AlexIIL** [comment]
Closing this as it doesn't make much sense with a full config file. Although I could have an image constant for visibleWidth, visibleHeight, visibleStartX and visibleStartY to allow this to happen properly. (That probably won't make much sense right now, it's for features in the next minor version)
