### ISSUE TITLE
Radial progess bar.

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#40]
whether it is possible to make radial progress bar?

Example:
![progress-bar-type-1](https://cloud.githubusercontent.com/assets/6783568/10218264/1f4ab09e-683e-11e5-9312-bae5ee5bb943.png)

**Comment by AlexIIL** [comment]
Not at the moment unfortunately, only rectangular progress is supported

**Comment by Tsyklop** [comment]
Thanks.
