### ISSUE TITLE
Animated elements

### ISSUE THREAD

**Issue by unplugred** [AlexIIL/BetterLoadingScreen#41]
I would like to have an animated element in my loading screen,
like a rotating block.
How can I do that?
Thanks, Pie.

**Comment by AlexIIL** [comment]
Ah. You can't do it in 1.7.10 atm, but you WILL be able to do it with BLS 1.4.x for 1.8. When I stop porting Buildcraft for a few days, I will finish it and release it.

(Sorry! I'll reply to this when I do release it)
