### ISSUE TITLE
A visual bug when loading

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#43]
look video: https://youtu.be/HdduGJAK-AQ

time: 0:45 - 0:52.

**Comment by AlexIIL** [comment]
So it seems the issue happens during "Not Enough Resources" is being shown, so when "Realistic terrain generation" is being loaded. Can you check to see if removing RTG fixes the problem?

**Comment by Tsyklop** [comment]
I remove RTG and NER and problem still here.

**Comment by AlexIIL** [comment]
I'm not sure then. I'll have a play around to see if I can reproduce it.

**Comment by Tsyklop** [comment]
here: https://drive.google.com/file/d/0B9c2x-D6eUzeX3JBX3FSMy1HMU0/view?usp=sharing

I`m using MultiMC. Forge 10.13.4.1614 and LiteLoader 1.7.10_04

**Comment by Tsyklop** [comment]
@AlexIIL can you fix this?

**Comment by AlexIIL** [comment]
Sorry, after some testing (and re-reading the code) I realised that I did my colour clearing in the wrong order.... I'll put a Jar here shortly...

**Comment by AlexIIL** [comment]
Can you try with this jar? (remove the ".zip" from the file name, github wouldn't let me upload a jar file directly) [BetterLoadingScreen-1.3.9.jar.zip](https://github.com/AlexIIL/BetterLoadingScreen/files/102074/BetterLoadingScreen-1.3.9.jar.zip)

**Comment by Tsyklop** [comment]
work. thanks

**Comment by Tsyklop** [comment]
@AlexIIL Can you paste BLS 1.3.9 on CurseForge?
