### ISSUE TITLE
Get on with updating it ya lazy sod!

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/BetterLoadingScreen#45]
- [x] Submit a forge PR that can override forge's loading screen
  - Have it accepted (this was denied)
  - Investigate using reflection to make it work (this was too tedious)
  - [x] Use a coremod to make it work
- [x] Simplify the element factories
- [x] Simplify the progress bar abstraction, removing history?

**Comment by tenten8401** [comment]
Just thought i'd let you know, in order to override the forge loading screen, you can use /config/splash.properties, this allows for manually setting enabled=false, which is a fairly simple step to do for modpack creators. :)

BTW, I had to do this to get the 1.7.10 version of it working on the later forge versions. Also, I appreciate that you're working on this again.

**Comment by AlexIIL** [comment]
@tenten8401 thats not quite what I need to do - at the moment I use ASM on forge in order to use forge's progress stuffs (a VERY hacky thing todo), and a forge PR would allow me to stop using that ASM in favour of using some source code directly. It's not a change you would notice as a player though, it just makes the codebase a lot cleaner.

(Also this would stop you from needing to change the config, but it's a minor detail as I could already do that with ASM).

**Comment by tenten8401** [comment]
I'd be willing to donate a couple bucks if you need some motivation.

**Comment by AlexIIL** [comment]
@tenten8401 its more that I'm getting BuildCraft up to 1.10.2 and I don't have enough time to do the other modding projects as well.

**Comment by AlexIIL** [comment]
Although I occasionally take breaks from BC mainline so this might be finished during one of those :)

**Comment by tenten8401** [comment]
Ah, BuildCraft would be a lot more fun for 1.10.2! :P
Don't stress over the loading screen too much.

**Comment by AlexIIL** [comment]
I released a build for 1.12.2  and never closed this issue, woops.
