### ISSUE TITLE
Do not create a configuration file

### ISSUE THREAD

**Issue by ghost** [AlexIIL/BetterLoadingScreen#46]
Hello! I am using the latest version 1.7.10 and I can not figure out how to configure this mode. I have read that there should be images.json, but I do not have it anywhere. Help me please.

**Comment by AlexIIL** [comment]
If you have run it at least once, then it should create a file (in your base MC directory) at "./config/BetterLoadingScreen/images.json". Does the file not appear there?

**Comment by ghost** [comment]
Found! Somehow, a folder is created on the desktop.

**Comment by AlexIIL** [comment]
That sounds odd. Unless you have set MC's launch directory to your desktop it probably shouldn't be doing that...

**Comment by tmvkrpxl0** [comment]
i have same problem, i can find customloadingscreen.cfg in config folder, but i can't find anything else
i use 1.4.0.3 for 1.12.2
