### ISSUE TITLE
Get screen width on 1.7?

### ISSUE THREAD

**Issue by ghost** [AlexIIL/BetterLoadingScreen#62]
Is it possible to stretch the image to the corners in 1.7? If not, could I get the 1.7 source to look myself at it?

**Comment by AlexIIL** [comment]
No, due to the 1.7.10 code being much simpler than the 1.12.2 code.

https://github.com/AlexIIL/BetterLoadingScreen_1.7

**Comment by AlexIIL** [comment]
Actually judging by https://github.com/AlexIIL/BetterLoadingScreen_1.7/commit/7ae4f503c8833e23ce4c71abaca6bb2137c5bbbc it looks like if you use 0 for the width + height then it uses the screens width, woops.

**Comment by ghost** [comment]
Yep, setting both to 0 worked perfectly, thanks for the help
