### ISSUE TITLE
GregTech 5 compatibility

### ISSUE THREAD

**Issue by ghost** [AlexIIL/BetterLoadingScreen#63]
I would like to add Custom Loading Screen to a pack containing GregTech 5 unofficial and more than 20'000 materials that are registered, which is visile during loading time. Would it be possible to get a compat "fix" that displays their registration? (It's on 1.7.10)

**Comment by jackowski626** [comment]
I have set up the 1.7 code in eclipse but it seems like the class LoadingScreenLoadPlugin doesn't load. ProgressDisplayer.start(coremodLocation); doesn't run which results in a variable being null and crashing the game. Any ideas with that?

**Comment by ghost** [comment]
I got to grabbing the registered material with reflection with a timer in post init (since I don't have hooks for that), but I can't run `ProgressDisplayer.displayProgress(text, percent);` from the timer. Any insights? If you would like to help, I can reach out in twitter dms, otherwise you can close the issue and I'll continue digging

**Comment by AlexIIL** [comment]
I haven't looked at this yet, sorry.

>  but I can't run ProgressDisplayer.displayProgress(text, percent); from the timer

What sort of timer are you using? In theory that should if GT5-U called it every so often (perhaps everytime a material is registered).

**Comment by ghost** [comment]
I'm using a normal timer. I'm trying to force a text and percent render in ModLoadingListener but it seems like I can't really do that, I get an opengl not initialized error. What I'm trying now is to put the timer in MinecraftDisplayer itself. Edit: still getting opengl error.
https://paste.dimdev.org/zukuruzote.cs
https://paste.dimdev.org/oxezuwerin.rb

**Comment by AlexIIL** [comment]
Ah, ok. Unfortunately OpenGL doesn't work that way - all rendering calls must be on the main thread, which likely means calling it directly in whatever method registers GT5U materials.

**Comment by ghost** [comment]
Calling from main thread worked
