### ISSUE TITLE
How to make slideshow?

### ISSUE THREAD

**Issue by Exzept1on** [AlexIIL/BetterLoadingScreen#66]

**Comment by AlexIIL** [comment]
Temporary instructions, I'll update these when it's been tested to work a bit:

1. Download [Custom Loading Screen 0.5.0-pre.1 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/3208087)
2. In `config/customloadingscreen.cfg` Change `S:screen_config` to `S:screen_config=sample/slideshow`
3. Create a folder `config/customloadingscreen/`
4. Add your slideshow images in `config/customloadingscreen/` named `slideshow_1.png`, `slideshow_2.png`, `slideshow_3.png`, etc

**Comment by AlexIIL** [comment]
Additional instructions, if you want to tweak the slideshow itself:

1. Download [Custom Loading Screen 1.5.1 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/3235316)
2. In `config/customloadingscreen.cfg` Change `S:screen_config` to `S:screen_config=config/slideshow`
3. Create a folder `config/customloadingscreen/`
4. Add your slideshow images in `config/customloadingscreen/` named `slideshow_1.png`, `slideshow_2.png`, `slideshow_3.png`, etc
5. Copy the contents of [this file](https://raw.githubusercontent.com/AlexIIL/CustomLoadingScreen/1.4.x/src/main/resources/assets/customloadingscreen/sample/config/slideshow.json) into a new file in `config/customloadingscreen/slideshow.json`.
6. Change any of the 4 constants at the top of the file to tweak the slideshow a little bit.

**Comment by ghost** [comment]
This didn't work for me, I can't seem to get the slideshow feature to work with the latest version of customloadingscreen.
