### ISSUE TITLE
1.5.7 on curseforge

### ISSUE THREAD

**Issue by Exzept1on** [AlexIIL/BetterLoadingScreen#75]
You have fixed the problem of random crashes of minecraft with CLS. But we didn't download the curseforge version, since my modpack uses CLS and is published on Curse, I need version 1.5.7 on curseforge, and I think many others.

https://github.com/AlexIIL/CustomLoadingScreen/issues/73#issuecomment-1003086318

**Comment by AlexIIL** [comment]
I've published [1.5.7](https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/3769828) to curseforge - sorry for the delay!

**Comment by Exzept1on** [comment]
Thanks 👍
