### ISSUE TITLE
Minecraft Forge has its own loading screen now

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/BetterLoadingScreen#8]
What should happen? Does anybody use the configuration features of this mod (or would like to use if it was documented properly)
http://strawpoll.me/4173361

**Comment by Gotolei** [comment]
I can't seem to find any details on Forge's loading screen. Where is it documented, and what does it look like?

What makes this mod useful for me personally is its ability to have the progress bar *as its own window* that I can keep on top of whatever I'm doing, as opposed to having to switch workspace/window to minecraft just to check the progress.

**Comment by AlexIIL** [comment]
I didn't honestly think anyone used that feature, and I was going to remove it for 1.4.0. Might not now! Earlier today (21/4/15) cpw tweeted details on forge's loading screen (his twitter handle is "voxcpw"), and tweeted a file (I will link his twitter soon) with the forge's loading screen. Note that forge's loading screen is in alpha right now, but it does look pretty good (a video is on cpw's twitter).

**Comment by AlexIIL** [comment]
Ok, closing this until forge has a standard API for it.
